name: Assembly Homology Service tests

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    # run workflow when merging to main or develop
    branches:
      - main
      - master
      - develop

jobs:

  assembly_homology_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: '8'
            mongo: 'mongodb-linux-x86_64-ubuntu2204-7.0.4'
          - java: '11'
            mongo: 'mongodb-linux-x86_64-ubuntu2004-4.4.29'
    steps:
      - uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}

      - name: Install dependencies and set up test config
        shell: bash
        run: |
          export HOMEDIR=`pwd`

          # move to parent dir of homedir to install binaries etc
          cd ..
          
          # Set up mash
          wget https://github.com/marbl/Mash/releases/download/v2.0/mash-Linux64-v2.0.tar
          tar -xf mash-Linux64-v2.0.tar
          cd mash-Linux64-v2.0
          MP=`pwd`
          echo "MASH_PATH=$MP" >> "$GITHUB_ENV"
          cd ..

          # set up mongo
          wget -q http://fastdl.mongodb.org/linux/${{matrix.mongo}}.tgz
          tar xfz ${{matrix.mongo}}.tgz
          export MONGOD=`pwd`/${{matrix.mongo}}/bin/mongod

          # set up test config
          cd $HOMEDIR
          cp -n test.cfg.example test.cfg
          sed -i "s#^test.mongo.exe.*#test.mongo.exe=$MONGOD#" test.cfg
          cat test.cfg

      - name: Run tests
        shell: bash
        run: |
          PATH=$PATH:$MASH_PATH
          echo $PATH
          ./gradlew test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
